import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import CustomTable from "../component/CustomTable";
import styles from "../styles/Home.module.css";
import All from "../component/All";
// export async function getServerSideProps() {
//   const res = await fetch(`http://localhost:8080/api/all`);
//   const data = await res.json();

//   return { props: { todos: data } };
// }

export default function Home() {
  // const [radioValue, setRadioValue] = useState("");
  // const [searchValue, setSearchValue] = useState("");
  // console.log(radioValue);
  // console.log(searchValue);
  // return (
  //   <div className={styles.container}>
  //     <Head>
  //       <title>Create Next App</title>
  //       <meta name="description" content="Generated by create next app" />
  //       <link rel="icon" href="/favicon.ico" />
  //     </Head>
  //     <div className={styles.parent}>
  //       <div className={styles.div2}>
  //         {" "}
  //         <div className={styles.searchbar}>
  //           <div className={styles.searchSection}>
  //             <input
  //               type="text"
  //               className={styles.searchInput}
  //               value={searchValue}
  //               onChange={(e) => {
  //                 setSearchValue(e.target.value);
  //               }}
  //             ></input>
  //             <button>Search</button>
  //           </div>
  //           <div className={styles.category}>
  //             <label className={styles.radioName}>
  //               <input
  //                 className={styles.inpu}
  //                 type="radio"
  //                 name="asd"
  //                 value="points"
  //                 onChange={(e) => {
  //                   setRadioValue(e.target.value);
  //                 }}
  //               />
  //               <div className={styles.raddesign}></div>
  //               <div className={styles.text}>By Points</div>
  //             </label>
  //             <label className={styles.radioName}>
  //               <input
  //                 className={styles.inpu}
  //                 type="radio"
  //                 name="asd"
  //                 value="title"
  //                 onChange={(e) => {
  //                   setRadioValue(e.target.value);
  //                 }}
  //               />
  //               <div className={styles.raddesign}></div>
  //               <div className={styles.text}>By Name</div>
  //             </label>
  //             <label className={styles.radioName}>
  //               <input
  //                 className={styles.inpu}
  //                 type="radio"
  //                 name="asd"
  //                 value="description"
  //                 onChange={(e) => {
  //                   setRadioValue(e.target.value);
  //                 }}
  //               />
  //               <div className={styles.raddesign}></div>
  //               <div className={styles.text}>By Description</div>
  //             </label>
  //             <label className={styles.radioName}>
  //               <input
  //                 className={styles.inpu}
  //                 type="radio"
  //                 name="asd"
  //                 value="taster_name"
  //                 onChange={(e) => {
  //                   setRadioValue(e.target.value);
  //                 }}
  //               />
  //               <div className={styles.raddesign}></div>
  //               <div className={styles.text}>By Taster</div>
  //             </label>
  //             <label className={styles.radioName}>
  //               <input
  //                 className={styles.inpu}
  //                 type="radio"
  //                 name="asd"
  //                 value="price"
  //                 onChange={(e) => {
  //                   setRadioValue(e.target.value);
  //                 }}
  //               />
  //               <div className={styles.raddesign}></div>
  //               <div className={styles.text}>By Price</div>
  //             </label>
  //             <label className={styles.radioName}>
  //               <input
  //                 className={styles.inpu}
  //                 type="radio"
  //                 name="asd"
  //                 value="variety"
  //                 onChange={(e) => {
  //                   setRadioValue(e.target.value);
  //                 }}
  //               />
  //               <div className={styles.raddesign}></div>
  //               <div className={styles.text}>By Variety</div>
  //             </label>
  //             <label className={styles.radioName}>
  //               <input
  //                 className={styles.inpu}
  //                 type="radio"
  //                 name="asd"
  //                 value="region_1"
  //                 onChange={(e) => {
  //                   setRadioValue(e.target.value);
  //                 }}
  //               />
  //               <div className={styles.raddesign}></div>
  //               <div className={styles.text}>By Region</div>
  //             </label>
  //             <label className={styles.radioName}>
  //               <input
  //                 className={styles.inpu}
  //                 type="radio"
  //                 name="asd"
  //                 value="province"
  //                 onChange={(e) => {
  //                   setRadioValue(e.target.value);
  //                 }}
  //               />
  //               <div className={styles.raddesign}></div>
  //               <div className={styles.text}>By Province</div>
  //             </label>
  //             <label className={styles.radioName}>
  //               <input
  //                 className={styles.inpu}
  //                 type="radio"
  //                 name="asd"
  //                 value="country"
  //                 onChange={(e) => {
  //                   setRadioValue(e.target.value);
  //                 }}
  //               />
  //               <div className={styles.raddesign}></div>
  //               <div className={styles.text}>By Country</div>
  //             </label>
  //             <label className={styles.radioName}>
  //               <input
  //                 className={styles.inpu}
  //                 type="radio"
  //                 name="asd"
  //                 value="winery"
  //                 onChange={(e) => {
  //                   setRadioValue(e.target.value);
  //                 }}
  //               />
  //               <div className={styles.raddesign}></div>
  //               <div className={styles.text}>By Winery</div>
  //             </label>
  //           </div>
  //         </div>
  //       </div>
  //       <div className={styles.div3}>
  //         <CustomTable />
  //       </div>
  //     </div>
  //   </div>
  // );
  return <All />;
}
