import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import CustomTableSearch from "../component/CustomTableSearch";
import styles from "../styles/Home.module.css";
import Search from "../component/Search";
import BackButton from "../component/BackButton";
import RangeSearch from "../component/RangeSearch";

export default function SearchByRange() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.parent}>
        <div className={styles.div2}>
          <Search />
        </div>
        <div className={styles.div3}>
          {/* <BackButton /> */}
          <RangeSearch />
        </div>
      </div>
    </div>
  );
}
