import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import CustomTable from "../component/CustomTable";
import styles from "../styles/Home.module.css";
import Search from "./Search";

// export async function getServerSideProps() {
//   const res = await fetch(`http://localhost:8080/api/all`);
//   const data = await res.json();

//   return { props: { todos: data } };
// }

export default function All() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.parent}>
        <div className={styles.div2}>
          <Search />
        </div>
        <div className={styles.div3}>
          <CustomTable />
        </div>
      </div>
    </div>
  );
}
